FROM node:8.11-slim

RUN yarn global add lerna@3.3.0 node-pre-gyp@0.11.0 tslint@5.11.0 typescript@3.0.1 webpack3@4.0.0
RUN apt-get update && \
    apt-get install -y \
      git \
      python \
      xsltproc \
      build-essential && \
    rm -rf /var/lib/apt/lists

WORKDIR /app

COPY . /app
RUN lerna bootstrap && yarn install && yarn build
RUN yarn global add ts-node-dev
RUN find . -type d -name puppeteer -exec rm -rf {} + && \
    find . -type d -name karma-spec-reporter -exec rm -rf {} + && \
    find . -type d -name prompt -exec rm -rf {} +

WORKDIR /app/packages/metering-kit-node/

CMD ["ts-node-dev", "./src/bin/main.js", "--config", "/etc/config.json"]
