<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
    version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output method="text" encoding="Windows-1252"/>

    <xsl:template match="/" >
// Autogenerated file
import {<xsl:for-each select="/operator/events/event">
  I<xsl:value-of select="./@name"/>Event<xsl:if test='position() != last()'>,</xsl:if></xsl:for-each> } from './interfaces'

export default interface IOperatorTransportCallback {<xsl:for-each select="/operator/events/event">
  on<xsl:value-of select="./@name"/> (event: I<xsl:value-of select="./@name"/>Event): Promise&lt;void></xsl:for-each>
}
</xsl:template>
</xsl:stylesheet>
